from django.contrib import admin
from .models import (
Alabama,
Alaska,
Arizona,
Arkansas,
California,
Colorado,
Connecticut,
Delaware,
Florida,
Georgia,
Hawaii,
Idaho,
Illinois,
Indiana,
Iowa,
Kansas,
Kentucky,
Louisiana,
Maine,
Maryland,
Massachusetts,
Michigan,
Minnesota,
Mississippi,
Missouri,
Montana,
Nebraska,
Nevada,
NewHampshire,
NewJersey,
NewMexico,
NewYork,
NorthCarolina,
NorthDakota,
Ohio,
Oklahoma,
Oregon,
Pennsylvania,
RhodeIsland,
SouthCarolina,
SouthDakota,
Tennessee,
Texas,
Utah,
Vermont,
Virginia,
Washington,
WestVirginia,
Wisconsin,
Wyoming,
)

# Register your models here.
admin.site.register(Alabama)
admin.site.register(Alaska)
admin.site.register(Arizona)
admin.site.register(Arkansas)
admin.site.register(California)
admin.site.register(Colorado)
admin.site.register(Connecticut)
admin.site.register(Delaware)
admin.site.register(Florida)
admin.site.register(Georgia)
admin.site.register(Hawaii)
admin.site.register(Idaho)
admin.site.register(Illinois)
admin.site.register(Indiana)
admin.site.register(Iowa)
admin.site.register(Kansas)
admin.site.register(Kentucky)
admin.site.register(Louisiana)
admin.site.register(Maine)
admin.site.register(Maryland)
admin.site.register(Massachusetts)
admin.site.register(Michigan)
admin.site.register(Minnesota)
admin.site.register(Mississippi)
admin.site.register(Missouri)
admin.site.register(Montana)
admin.site.register(Nebraska)
admin.site.register(Nevada)
admin.site.register(NewHampshire)
admin.site.register(NewJersey)
admin.site.register(NewMexico)
admin.site.register(NewYork)
admin.site.register(NorthCarolina)
admin.site.register(NorthDakota)
admin.site.register(Ohio)
admin.site.register(Oklahoma)
admin.site.register(Oregon)
admin.site.register(Pennsylvania)
admin.site.register(RhodeIsland)
admin.site.register(SouthCarolina)
admin.site.register(SouthDakota)
admin.site.register(Tennessee)
admin.site.register(Texas)
admin.site.register(Utah)
admin.site.register(Vermont)
admin.site.register(Virginia)
admin.site.register(Washington)
admin.site.register(WestVirginia)
admin.site.register(Wisconsin)
admin.site.register(Wyoming)
