from django.urls import path
from .views import (
AlabamaListView,
AlaskaListView,
ArizonaListView,
ArkansasListView,
CaliforniaListView,
ColoradoListView,
ConnecticutListView,
DelawareListView,
FloridaListView,
GeorgiaListView,
HawaiiListView,
IdahoListView,
IllinoisListView,
IndianaListView,
IowaListView,
KansasListView,
KentuckyListView,
LouisianaListView,
MaineListView,
MarylandListView,
MassachusettsListView,
MichiganListView,
MinnesotaListView,
MississippiListView,
MissouriListView,
MontanaListView,
NebraskaListView,
NevadaListView,
NewHampshireListView,
NewJerseyListView,
NewMexicoListView,
NewYorkListView,
NorthCarolinaListView,
NorthDakotaListView,
OhioListView,
OklahomaListView,
OregonListView,
PennsylvaniaListView,
RhodeIslandListView,
SouthCarolinaListView,
SouthDakotaListView,
TennesseeListView,
TexasListView,
UtahListView,
VermontListView,
VirginiaListView,
WashingtonListView,
WestVirginiaListView,
WisconsinListView,
WyomingListView,
akcalculate,

)
from . import views


urlpatterns = [
    path('', views.home, name = 'graphs-home'),
    path('info/', views.info, name = 'graphs-state-info'),
    path('alabama/', views.alabama, name = 'graphs-alabama'),
    path('alaska/', views.alaska, name = 'graphs-alaska'),
    path('arizona/', views.arizona, name = 'graphs-arizona'),
    path('arkansas/', views.arkansas, name = 'graphs-arkansas'),
    path('california/', views.california, name = 'graphs-california'),
    path('colorado/', views.colorado, name = 'graphs-colorado'),
    path('connecticut/', views.connecticut, name = 'graphs-connecticut'),
    path('delaware/', views.delaware, name = 'graphs-delaware'),
    path('florida/', views.florida, name = 'graphs-florida'),
    path('georgia/', views.georgia, name = 'graphs-georgia'),
    path('hawaii/', views.hawaii, name = 'graphs-hawaii'),
    path('idaho/', views.idaho, name = 'graphs-idaho'),
    path('illinois/', views.illinois, name = 'graphs-illinois'),
    path('indiana/', views.indiana, name = 'graphs-indiana'),
    path('iowa/', views.iowa, name = 'graphs-iowa'),
    path('kansas/', views.kansas, name = 'graphs-kansas'),
    path('kentucky/', views.kentucky, name = 'graphs-kentucky'),
    path('louisiana/', views.louisiana, name = 'graphs-louisiana'),
    path('maine/', views.maine, name = 'graphs-maine'),
    path('maryland/', views.maryland, name = 'graphs-maryland'),
    path('massachusetts/', views.massachusetts, name = 'graphs-massachusetts'),
    path('michigan/', views.michigan, name = 'graphs-michigan'),
    path('minnesota/', views.minnesota, name = 'graphs-minnesota'),
    path('mississippi/', views.mississippi, name = 'graphs-mississippi'),
    path('missouri/', views.missouri, name = 'graphs-missouri'),
    path('montana/', views.montana, name = 'graphs-montana'),
    path('nebraska/', views.nebraska, name = 'graphs-nebraska'),
    path('nevada/', views.nevada, name = 'graphs-nevada'),
    path('new-hampshire/', views.new_hampshire, name = 'graphs-new-hampshire'),
    path('new-jersey/', views.new_jersey, name = 'graphs-new-jersey'),
    path('new-mexico/', views.new_mexico, name = 'graphs-new-mexico'),
    path('new-york/', views.new_york, name = 'graphs-new-york'),
    path('north-carolina/', views.north_carolina, name = 'graphs-north-carolina'),
    path('north-dakota/', views.north_dakota, name = 'graphs-north-dakota'),
    path('ohio/', views.ohio, name = 'graphs-ohio'),
    path('oklahoma/', views.oklahoma, name = 'graphs-oklahoma'),
    path('oregon/', views.oregon, name = 'graphs-oregon'),
    path('pennsylvania/', views.pennsylvania, name = 'graphs-pennsylvania'),
    path('rhode-island/', views.rhode_island, name = 'graphs-rhode-island'),
    path('south-carolina/', views.south_carolina, name = 'graphs-south-carolina'),
    path('south-dakota/', views.south_dakota, name = 'graphs-south-dakota'),
    path('tennessee/', views.tennessee, name = 'graphs-tennessee'),
    path('texas/', views.texas, name = 'graphs-texas'),
    path('utah/', views.utah, name = 'graphs-utah'),
    path('vermont/', views.vermont, name = 'graphs-vermont'),
    path('virginia/', views.virginia, name = 'graphs-virginia'),
    path('washington/', views.washington, name = 'graphs-washington'),
    path('west-virginia/', views.west_virginia, name = 'graphs-west-virginia'),
    path('wisconsin/', views.wisconsin, name = 'graphs-wisconsin'),
    path('wyoming/', views.wyoming, name = 'graphs-wyoming'),
    path('conclusion/', views.conclusion, name = 'graphs-conclusion'),
    path('alabama-predict/', views.alcalculate, name = 'al-predict'),
    path('alaska-predict/', views.akcalculate, name = 'ak-predict'),
    path('arizona-predict', views.azcalculate, name = 'az-predict'),
    path('arkansas-predict', views.arcalculate, name = 'ar-predict'),
    path('california-predict', views.cacalculate, name = 'ca-predict'),
    path('colorado-predict', views.cocalculate, name = 'co-predict'),
    path('connecticut-predict', views.ctcalculate, name = 'ct-predict'),
    path('delaware-predict', views.decalculate, name = 'de-predict'),
    path('florida-predict', views.flcalculate, name = 'fl-predict'),
    path('georgia-predict', views.gacalculate, name = 'ga-predict'),
    path('hawaii-predict', views.hicalculate, name = 'hi-predict'),
    path('idaho-predict', views.idcalculate, name = 'id-predict'),
    path('illinois-predict', views.ilcalculate, name = 'il-predict'),
    path('indiana-predict', views.incalculate, name = 'in-predict'),
    path('iowa-predict', views.iacalculate, name = 'ia-predict'),
    path('kansas-predict', views.kscalculate, name = 'ks-predict'),
    path('kentucky-predict', views.kycalculate, name = 'ky-predict'),
    path('louisiana-predict', views.lacalculate, name = 'la-predict'),
    path('maine-predict', views.mecalculate, name = 'me-predict'),
    path('maryland-predict', views.mdcalculate, name = 'md-predict'),
    path('massachusetts-predict', views.macalculate, name = 'ma-predict'),
    path('michigan-predict', views.micalculate, name = 'mi-predict'),
    path('minnesota-predict', views.mncalculate, name = 'mn-predict'),
    path('mississippi-predict', views.mscalculate, name = 'ms-predict'),
    path('missouri-predict', views.mocalculate, name = 'mo-predict'),
    path('montana-predict', views.mtcalculate, name = 'mt-predict'),
    path('nebraska-predict', views.necalculate, name = 'ne-predict'),
    path('nevada-predict', views.nvcalculate, name = 'nv-predict'),
    path('new-hampshire-predict', views.nhcalculate, name = 'nh-predict'),
    path('new-jersey-predict', views.njcalculate, name = 'nj-predict'),
    path('new-mexico-predict', views.nmcalculate, name = 'nm-predict'),
    path('new-york-predict', views.nycalculate, name = 'ny-predict'),
    path('north-carolina-predict', views.nccalculate, name = 'nc-predict'),
    path('north-dakota-predict', views.ndcalculate, name = 'nd-predict'),
    path('ohio-predict', views.ohcalculate, name = 'oh-predict'),
    path('oklahoma-predict', views.okcalculate, name = 'ok-predict'),
    path('oregon-predict', views.orcalculate, name = 'or-predict'),
    path('pennsylvania-predict', views.pacalculate, name = 'pa-predict'),
    path('rhode-island-predict', views.ricalculate, name = 'ri-predict'),
    path('south-carolina-predict', views.sccalculate, name = 'sc-predict'),
    path('south-dakota-predict', views.sdcalculate, name = 'sd-predict'),
    path('tennessee-predict', views.tncalculate, name = 'tn-predict'),
    path('texas-predict', views.txcalculate, name = 'tx-predict'),
    path('utah-predict', views.utcalculate, name = 'ut-predict'),
    path('vermont-predict', views.vtcalculate, name = 'vt-predict'),
    path('virginia-predict', views.vacalculate, name = 'va-predict'),
    path('washington-predict', views.wacalculate, name = 'wa-predict'),
    path('west-virginia-predict', views.wvcalculate, name = 'wv-predict'),
    path('wisconsin-predict', views.wicalculate, name = 'wi-predict'),
    path('wyoming-predict', views.wycalculate, name = 'wy-predict'),
    path('alabama/', AlabamaListView.as_view(), name = 'graphs-alabama'),
    path('alaska/', AlaskaListView.as_view(), name = 'graphs-alaska'),
    path('arizona/', ArizonaListView.as_view(), name = 'graphs-arizona'),
    path('arkansas/', ArkansasListView.as_view(), name = 'graphs-arkansas'),
    path('california/', CaliforniaListView.as_view(), name = 'graphs-california'),
    path('colorado/', ColoradoListView.as_view(), name = 'graphs-colorado'),
    path('connecticut/', ConnecticutListView.as_view(), name = 'graphs-connecticut'),
    path('delaware/', DelawareListView.as_view(), name = 'graphs-delaware'),
    path('florida/', FloridaListView.as_view(), name = 'graphs-florida'),
    path('georgia/', GeorgiaListView.as_view(), name = 'graphs-georgia'),
    path('hawaii/', HawaiiListView.as_view(), name = 'graphs-hawaii'),
    path('idaho/', IdahoListView.as_view(), name = 'graphs-idaho'),
    path('illinois/', IllinoisListView.as_view(), name = 'graphs-illinois'),
    path('indiana/', IndianaListView.as_view(), name = 'graphs-indiana'),
    path('iowa/', IowaListView.as_view(), name = 'graphs-iowa'),
    path('kansas/', KansasListView.as_view(), name = 'graphs-kansas'),
    path('kentucky/', KentuckyListView.as_view(), name = 'graphs-kentucky'),
    path('louisiana/', LouisianaListView.as_view(), name = 'graphs-louisiana'),
    path('maine/', MaineListView.as_view(), name = 'graphs-maine'),
    path('maryland/', MarylandListView.as_view(), name = 'graphs-maryland'),
    path('massachusetts/', MassachusettsListView.as_view(), name = 'graphs-massachusetts'),
    path('michigan/', MichiganListView.as_view(), name = 'graphs-michigan'),
    path('minnesota/', MinnesotaListView.as_view(), name = 'graphs-minnesota'),
    path('mississippi/', MississippiListView.as_view(), name = 'graphs-mississippi'),
    path('missouri/', MissouriListView.as_view(), name = 'graphs-missouri'),
    path('montana/', MontanaListView.as_view(), name = 'graphs-montana'),
    path('nebraska/', NebraskaListView.as_view(), name = 'graphs-nebraska'),
    path('nevada/', NevadaListView.as_view(), name = 'graphs-nevada'),
    path('new-hampshire/', NewHampshireListView.as_view(), name = 'graphs-new-hampshire'),
    path('new-jersey/', NewJerseyListView.as_view(), name = 'graphs-new-jersey'),
    path('new-mexico/', NewMexicoListView.as_view(), name = 'graphs-new-mexico'),
    path('new-york/', NewYorkListView.as_view(), name = 'graphs-new-york'),
    path('north-carolina/', NorthCarolinaListView.as_view(), name = 'graphs-north-carolina'),
    path('north-dakota/', NorthDakotaListView.as_view(), name = 'graphs-north-dakota'),
    path('ohio/', OhioListView.as_view(), name = 'graphs-ohio'),
    path('oklahoma/', OklahomaListView.as_view(), name = 'graphs-oklahoma'),
    path('oregon/', OregonListView.as_view(), name = 'graphs-oregon'),
    path('pennsylvania/', PennsylvaniaListView.as_view(), name = 'graphs-pennsylvania'),
    path('rhode-island/', RhodeIslandListView.as_view(), name = 'graphs-rhode-island'),
    path('south-carolina/', SouthCarolinaListView.as_view(), name = 'graphs-south-carolina'),
    path('south-dakota/', SouthDakotaListView.as_view(), name = 'graphs-south-dakota'),
    path('tennessee/', TennesseeListView.as_view(), name = 'graphs-tennessee'),
    path('texas/', TexasListView.as_view(), name = 'graphs-texas'),
    path('utah/', UtahListView.as_view(), name = 'graphs-utah'),
    path('vermont/', VermontListView.as_view(), name = 'graphs-vermont'),
    path('virginia/', VirginiaListView.as_view(), name = 'graphs-virginia'),
    path('washington/', WashingtonListView.as_view(), name = 'graphs-washington'),
    path('west-virginia/', WestVirginiaListView.as_view(), name = 'graphs-west-virginia'),
    path('wisconsin/', WisconsinListView.as_view(), name = 'graphs-wisconsin'),
    path('wyoming/', WyomingListView.as_view(), name = 'graphs-wyoming'),
]
