from django.urls import path
from .views import (
AlabamaListView,
AlaskaListView,
ArizonaListView,
ArkansasListView,
CaliforniaListView,
ColoradoListView,
ConnecticutListView,
DelawareListView,
FloridaListView,
GeorgiaListView,
HawaiiListView,
IdahoListView,
IllinoisListView,
IndianaListView,
IowaListView,
KansasListView,
KentuckyListView,
LouisianaListView,
MaineListView,
MarylandListView,
MassachusettsListView,
MichiganListView,
MinnesotaListView,
MississippiListView,
MissouriListView,
MontanaListView,
NebraskaListView,
NevadaListView,
NewHampshireListView,
NewJerseyListView,
NewMexicoListView,
NewYorkListView,
NorthCarolinaListView,
NorthDakotaListView,
OhioListView,
OklahomaListView,
OregonListView,
PennsylvaniaListView,
RhodeIslandListView,
SouthCarolinaListView,
SouthDakotaListView,
TennesseeListView,
TexasListView,
UtahListView,
VermontListView,
VirginiaListView,
WashingtonListView,
WestVirginiaListView,
WisconsinListView,
WyomingListView,
)
from . import views


urlpatterns = [
    path('', views.home, name = 'graphs-home'),
    path('info/', views.info, name = 'graphs-state-info'),
    path('alabama/', views.alabama, name = 'graphs-alabama'),
    path('alaska/', views.alaska, name = 'graphs-alaska'),
    path('arizona/', views.arizona, name = 'graphs-arizona'),
    path('arkansas/', views.arkansas, name = 'graphs-arkansas'),
    path('california/', views.california, name = 'graphs-california'),
    path('colorado/', views.colorado, name = 'graphs-colorado'),
    path('connecticut/', views.connecticut, name = 'graphs-connecticut'),
    path('delaware/', views.delaware, name = 'graphs-delaware'),
    path('florida/', views.florida, name = 'graphs-florida'),
    path('georgia/', views.georgia, name = 'graphs-georgia'),
    path('hawaii/', views.hawaii, name = 'graphs-hawaii'),
    path('idaho/', views.idaho, name = 'graphs-idaho'),
    path('illinois/', views.illinois, name = 'graphs-illinois'),
    path('indiana/', views.indiana, name = 'graphs-indiana'),
    path('iowa/', views.iowa, name = 'graphs-iowa'),
    path('kansas/', views.kansas, name = 'graphs-kansas'),
    path('kentucky/', views.kentucky, name = 'graphs-kentucky'),
    path('louisiana/', views.louisiana, name = 'graphs-louisiana'),
    path('maine/', views.maine, name = 'graphs-maine'),
    path('maryland/', views.maryland, name = 'graphs-maryland'),
    path('massachusetts/', views.massachusetts, name = 'graphs-massachusetts'),
    path('michigan/', views.michigan, name = 'graphs-michigan'),
    path('minnesota/', views.minnesota, name = 'graphs-minnesota'),
    path('mississippi/', views.mississippi, name = 'graphs-mississippi'),
    path('missouri/', views.missouri, name = 'graphs-missouri'),
    path('montana/', views.montana, name = 'graphs-montana'),
    path('nebraska/', views.nebraska, name = 'graphs-nebraska'),
    path('nevada/', views.nevada, name = 'graphs-nevada'),
    path('new-hampshire/', views.new_hampshire, name = 'graphs-new-hampshire'),
    path('new-jersey/', views.new_jersey, name = 'graphs-new-jersey'),
    path('new-mexico/', views.new_mexico, name = 'graphs-new-mexico'),
    path('new-york/', views.new_york, name = 'graphs-new-york'),
    path('north-carolina/', views.north_carolina, name = 'graphs-north-carolina'),
    path('north-dakota/', views.north_dakota, name = 'graphs-north-dakota'),
    path('ohio/', views.ohio, name = 'graphs-ohio'),
    path('oklahoma/', views.oklahoma, name = 'graphs-oklahoma'),
    path('oregon/', views.oregon, name = 'graphs-oregon'),
    path('pennsylvania/', views.pennsylvania, name = 'graphs-pennsylvania'),
    path('rhode-island/', views.rhode_island, name = 'graphs-rhode-island'),
    path('south-carolina/', views.south_carolina, name = 'graphs-south-carolina'),
    path('south-dakota/', views.south_dakota, name = 'graphs-south-dakota'),
    path('tennessee/', views.tennessee, name = 'graphs-tennessee'),
    path('texas/', views.texas, name = 'graphs-texas'),
    path('utah/', views.utah, name = 'graphs-utah'),
    path('vermont/', views.vermont, name = 'graphs-vermont'),
    path('virginia/', views.virginia, name = 'graphs-virginia'),
    path('washington/', views.washington, name = 'graphs-washington'),
    path('west-virginia/', views.west_virginia, name = 'graphs-west-virginia'),
    path('wisconsin/', views.wisconsin, name = 'graphs-wisconsin'),
    path('wyoming/', views.wyoming, name = 'graphs-wyoming'),
    path('alabama/', AlabamaListView.as_view(), name = 'graphs-alabama'),
    path('alaska/', AlaskaListView.as_view(), name = 'graphs-alaska'),
    path('arizona/', ArizonaListView.as_view(), name = 'graphs-arizona'),
    path('arkansas/', ArkansasListView.as_view(), name = 'graphs-arkansas'),
    path('california/', CaliforniaListView.as_view(), name = 'graphs-california'),
    path('colorado/', ColoradoListView.as_view(), name = 'graphs-colorado'),
    path('connecticut/', ConnecticutListView.as_view(), name = 'graphs-connecticut'),
    path('delaware/', DelawareListView.as_view(), name = 'graphs-delaware'),
    path('florida/', FloridaListView.as_view(), name = 'graphs-florida'),
    path('georgia/', GeorgiaListView.as_view(), name = 'graphs-georgia'),
    path('hawaii/', HawaiiListView.as_view(), name = 'graphs-hawaii'),
    path('idaho/', IdahoListView.as_view(), name = 'graphs-idaho'),
    path('illinois/', IllinoisListView.as_view(), name = 'graphs-illinois'),
    path('indiana/', IndianaListView.as_view(), name = 'graphs-indiana'),
    path('iowa/', IowaListView.as_view(), name = 'graphs-iowa'),
    path('kansas/', KansasListView.as_view(), name = 'graphs-kansas'),
    path('kentucky/', KentuckyListView.as_view(), name = 'graphs-kentucky'),
    path('louisiana/', LouisianaListView.as_view(), name = 'graphs-louisiana'),
    path('maine/', MaineListView.as_view(), name = 'graphs-maine'),
    path('maryland/', MarylandListView.as_view(), name = 'graphs-maryland'),
    path('massachusetts/', MassachusettsListView.as_view(), name = 'graphs-massachusetts'),
    path('michigan/', MichiganListView.as_view(), name = 'graphs-michigan'),
    path('minnesota/', MinnesotaListView.as_view(), name = 'graphs-minnesota'),
    path('mississippi/', MississippiListView.as_view(), name = 'graphs-mississippi'),
    path('missouri/', MissouriListView.as_view(), name = 'graphs-missouri'),
    path('montana/', MontanaListView.as_view(), name = 'graphs-montana'),
    path('nebraska/', NebraskaListView.as_view(), name = 'graphs-nebraska'),
    path('nevada/', NevadaListView.as_view(), name = 'graphs-nevada'),
    path('new-hampshire/', NewHampshireListView.as_view(), name = 'graphs-new-hampshire'),
    path('new-jersey/', NewJerseyListView.as_view(), name = 'graphs-new-jersey'),
    path('new-mexico/', NewMexicoListView.as_view(), name = 'graphs-new-mexico'),
    path('new-york/', NewYorkListView.as_view(), name = 'graphs-new-york'),
    path('north-carolina/', NorthCarolinaListView.as_view(), name = 'graphs-north-carolina'),
    path('north-dakota/', NorthDakotaListView.as_view(), name = 'graphs-north-dakota'),
    path('ohio/', OhioListView.as_view(), name = 'graphs-ohio'),
    path('oklahoma/', OklahomaListView.as_view(), name = 'graphs-oklahoma'),
    path('oregon/', OregonListView.as_view(), name = 'graphs-oregon'),
    path('pennsylvania/', PennsylvaniaListView.as_view(), name = 'graphs-pennsylvania'),
    path('rhode-island/', RhodeIslandListView.as_view(), name = 'graphs-rhode-island'),
    path('south-carolina/', SouthCarolinaListView.as_view(), name = 'graphs-south-carolina'),
    path('south-dakota/', SouthDakotaListView.as_view(), name = 'graphs-south-dakota'),
    path('tennessee/', TennesseeListView.as_view(), name = 'graphs-tennessee'),
    path('texas/', TexasListView.as_view(), name = 'graphs-texas'),
    path('utah/', UtahListView.as_view(), name = 'graphs-utah'),
    path('vermont/', VermontListView.as_view(), name = 'graphs-vermont'),
    path('virginia/', VirginiaListView.as_view(), name = 'graphs-virginia'),
    path('washington/', WashingtonListView.as_view(), name = 'graphs-washington'),
    path('west-virginia/', WestVirginiaListView.as_view(), name = 'graphs-west-virginia'),
    path('wisconsin/', WisconsinListView.as_view(), name = 'graphs-wisconsin'),
    path('wyoming/', WyomingListView.as_view(), name = 'graphs-wyoming'),
    path('conclusion/', views.conclusion, name = 'graphs-conclusion'),
]
