# Generated by Django 3.0.7 on 2020-07-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20200728_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='alabama',
            name='temperature_input',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
