# Generated by Django 3.0.7 on 2020-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_alabama_temperature_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('temperature_input', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alabama',
            name='temperature_input',
        ),
    ]
