# Generated by Django 3.0.7 on 2020-07-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0006_auto_20200729_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ArPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AzPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CoPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CtPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DePredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FlPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HiPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IdPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IlPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='KsPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='KyPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MdPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MePredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MiPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MnPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MoPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MsPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MtPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NcPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NdPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NePredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NhPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NjPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NmPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NvPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NyPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OhPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OkPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RiPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SdPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TnPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TxPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UtPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VtPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WaPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WiPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WvPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WyPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='alpredict',
            name='b',
        ),
        migrations.RemoveField(
            model_name='alpredict',
            name='m',
        ),
    ]
